exclude: '^\.claude/'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-json
        exclude: ^(.devcontainer/devcontainer.json|tests/test_planning/fixtures/workflows/invalid-bad-json.json)
      - id: pretty-format-json
        exclude: ^(.devcontainer/devcontainer.json|tests/test_planning/fixtures/workflows/invalid-bad-json.json)
        args: [--autofix, --no-sort-keys]
      - id: end-of-file-fixer
        exclude: \.md$
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.5"
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]
      - id: ruff-format
